<?php

/**
 * Adding our frameworks to the Panels variant form... this should really be
 * dependent on the panels module being on.
 */
function pdb_form_page_variant_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $options = array(
    'none' => 'None',
  );
  \Drupal::moduleHandler()->alter('pdb_presentations_alter', $options);

  $form['presentation'] = array(
    '#title' => t('Presentation'),
    '#type' => 'select',
    '#options' => $options,
    '#weight' => 0,
  );

}
