<?php

/**
 * Adding our frameworks to the Panels variant form.
 *
 * This should really be dependent on the panels module being on. Also it
 * doesn't actually do anything yet, so we should probably @TODO that.
 */
function pdb_form_page_variant_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $presentations = array(
    'none' => 'None',
  );
  $overrides = \Drupal::moduleHandler()->invokeAll('pdb_presentations', $presentations);

  $presentations += $overrides;

  $form['presentation'] = array(
    '#title' => t('Presentation'),
    '#type' => 'select',
    '#options' => $presentations,
    '#weight' => 0,
  );

}
