<?php

/**
 * Implements hook_pdp_markup_override().
 *
 * Specify our custom markup for ng2 blocks.
 */
function pdp_ng2_pdp_markup_override($component, $return) {
  $info = $component['info'];
  // Only override if presentation if ng2.
  if ($info['presentation'] == 'ng2') {
    $return = '<' . $info['machine_name'] . '></' . $info['machine_name'] . '>';
  }
  return $return;
}

/**
 * Implements hook_pdp_settings().
 *
 * Specify our custom drupalSettings for ng2 blocks.
 */
function pdp_ng2_pdp_settings($component, $settings) {
  $info = $component['info'];
  // Only override if presentation if ng2.
  if ($info['presentation'] == 'ng2') {
    if (!isset($settings['apps'])) {
      $settings['apps'] = array();
    }
    $settings['apps'][$info['machine_name']] = array(
      'uri' => $info['path']
    );
  }
  return $settings;
}

/**
 * Implements hook_pdp_libraries().
 *
 * Specify our custom library for ng2 blocks.
 */
function pdp_ng2_pdp_libraries($component, $libraries) {
  $info = $component['info'];
  // Only override if presentation if ng2.
  if ($info['presentation'] == 'ng2') {
    if (!isset($libraries['pdp_ng2/angular2'])) {
      $libraries += array(
        'pdp_ng2/angular2'
      );
    }
  }
  return $libraries;
}
